when@local:
  framework:
    cache:
      app: cache.adapter.redis
      system: cache.adapter.redis
      default_redis_provider: snc_redis.cache
      pools:
        redis.cache:
          adapter: cache.adapter.redis_tag_aware
          provider: '%env(REDIS_CACHE_DSN)%'

when@test:
  framework:
    cache:
      app: cache.adapter.array
      system: cache.adapter.array
      pools:
        redis.cache:
          adapter: cache.adapter.redis_tag_aware
          provider: '%env(REDIS_CACHE_DSN)%'